/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algos;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.PriorityQueue;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void foo() {
        PriorityQueue<Integer> queue = new PriorityQueue<>();
        //2, 4, 7, 1, 5, 3
        queue.offer(2);
        queue.offer(4);
        queue.offer(7);
        queue.offer(1);
        queue.remove();

        queue.offer(5);
        queue.remove();

        queue.offer(3);
        queue.remove();

        System.out.println(Arrays.toString(queue.toArray()));
    }
}
